INSERT INTO templates (name, slug, subdomain, description, category, display_order, is_active, view_count, click_count, created_at, updated_at) VALUES
('Doanh nghiệp', 'corporate', 'corporate', 'Mẫu website chuyên nghiệp cho các công ty và doanh nghiệp.', 'corporate', 1, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Agency / Digital Studio', 'agency', 'agency', 'Mẫu website hiện đại cho các công ty sáng tạo và agency.', 'agency', 2, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SaaS / Startup', 'saas', 'saas', 'Mẫu website tối ưu cho các sản phẩm phần mềm và startup.', 'saas', 3, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cửa hàng online', 'ecommerce', 'ecommerce', 'Mẫu website thương mại điện tử đầy đủ chức năng.', 'ecommerce', 4, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nhà hàng / Cafe', 'restaurant', 'restaurant', 'Mẫu website chuyên biệt cho nhà hàng và quán café.', 'restaurant', 5, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bất động sản', 'realestate', 'realestate', 'Mẫu website cho các công ty bất động sản và môi giới.', 'realestate', 6, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Blog / Magazine', 'blog', 'blog', 'Mẫu website cho blog cá nhân và tạp chí trực tuyến.', 'blog', 7, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Portfolio cá nhân', 'portfolio', 'portfolio', 'Mẫu website giới thiệu công việc và dự án cá nhân.', 'portfolio', 8, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Phòng khám / Nha khoa', 'medical', 'medical', 'Mẫu website chuyên dùng cho phòng khám và nha khoa.', 'medical', 9, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Trường học / Khoá học', 'education', 'education', 'Mẫu website cho các trường học, khoá học trực tuyến.', 'education', 10, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hội nghị / Sự kiện', 'event', 'event', 'Mẫu website tổ chức sự kiện, hội thảo, và hội nghị.', 'event', 11, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Đám cưới', 'wedding', 'wedding', 'Mẫu website lên kế hoạch và chia sẻ chi tiết đám cưới.', 'wedding', 12, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gym / Fitness', 'fitness', 'fitness', 'Mẫu website cho phòng tập thể dục và trung tâm fitness.', 'fitness', 13, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Từ thiện / NGO', 'nonprofit', 'nonprofit', 'Mẫu website cho các tổ chức từ thiện và phi lợi nhuận.', 'nonprofit', 14, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Khách sạn / Resort', 'travel', 'travel', 'Mẫu website cho khách sạn, resort, và dịch vụ du lịch.', 'travel', 15, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kiến trúc / Xây dựng', 'construction', 'construction', 'Mẫu website cho công ty kiến trúc và xây dựng.', 'construction', 16, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Salon / Spa', 'beauty', 'beauty', 'Mẫu website cho salon làm đẹp và dịch vụ spa.', 'beauty', 17, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Photography Studio', 'photography', 'photography', 'Mẫu website cho các studio chụp ảnh chuyên nghiệp.', 'photography', 18, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Đại lý xe', 'automotive', 'automotive', 'Mẫu website cho đại lý ôtô và cửa hàng phụ tùng.', 'automotive', 19, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Văn phòng luật', 'legal', 'legal', 'Mẫu website cho công ty luật và dịch vụ pháp lý.', 'legal', 20, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cửa hàng streetwear', 'shop-streetwear', 'shop-streetwear', 'Mẫu cửa hàng chuyên bán thời trang streetwear.', 'shop-streetwear', 21, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cửa hàng nội thất', 'shop-homegoods', 'shop-homegoods', 'Mẫu cửa hàng kinh doanh đồ nội thất và trang trí.', 'shop-homegoods', 22, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cửa hàng điện tử', 'shop-electronics', 'shop-electronics', 'Mẫu cửa hàng bán điện tử, máy tính, và phụ kiện.', 'shop-electronics', 23, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Blog công nghệ', 'blog-tech', 'blog-tech', 'Mẫu blog chuyên về công nghệ, khoa học, và đổi mới.', 'blog-tech', 24, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Blog lifestyle', 'blog-lifestyle', 'blog-lifestyle', 'Mẫu blog chia sẻ về cuộc sống, thời trang, và sức khỏe.', 'blog-lifestyle', 25, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Blog ẩm thực', 'blog-food', 'blog-food', 'Mẫu blog chia sẻ công thức, review nhà hàng, và ẩm thực.', 'blog-food', 26, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CRM bất động sản', 'crm-realestate', 'crm-realestate', 'Mẫu quản lý khách hàng và dự án bất động sản.', 'crm-realestate', 27, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CRM agency', 'crm-agency', 'crm-agency', 'Mẫu quản lý dự án, nhân sự, và khách hàng agency.', 'crm-agency', 28, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CRM phòng khám', 'crm-clinic', 'crm-clinic', 'Mẫu quản lý bệnh nhân, lịch hẹn, và dịch vụ phòng khám.', 'crm-clinic', 29, true, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
